export const GeologyEndpoints = {
  GET_PROJECTS: `/projects`,
  CREATE_PROJECT: `/project`,
  GET_PROJECT: (projectId: string) => `/project/${projectId}`,
  UPDATE_PROJECT: (projectId: string) => `/project/${projectId}`,
  DELETE_PROJECT: (projectId: string) => `/project/${projectId}`,
  CREATE_TRACKER: (projectId: string) => `/project/${projectId}/tracker`,
  GET_TRACKER: (projectId: string, trackerId: string) => `/project/${projectId}/tracker/${trackerId}`,
  UPDATE_TRACKER: (projectId: string, trackerId: string) => `/project/${projectId}/tracker/${trackerId}`,
  GET_TRACKERS_BY_PROJECT: (projectId: string) => `/project/${projectId}/trackers`,
  GET_TRACKERS: `/trackers`,
  DELETE_TRACKER: (projectId: string, trackerId: string) => `/project/${projectId}/tracker/${trackerId}`,
  RUN_TRACKER: (projectId: string, trackerId: string) => `/project/${projectId}/tracker/${trackerId}/run`,
  RUN_PROJECT: (projectId: string) => `/project/${projectId}/run`,
  BULK_CREATE_TRACKERS: (projectId: string) => `/project/${projectId}/tracker/bulk`,
  CREATE_PERSONA: (projectId: string) => `/project/${projectId}/persona`,
  GET_PERSONA: (projectId: string, personaId: string) => `/project/${projectId}/persona/${personaId}`,
  UPDATE_PERSONA: (projectId: string, personaId: string) => `/project/${projectId}/persona/${personaId}`,
  DELETE_PERSONA: (projectId: string, personaId: string) => `/project/${projectId}/persona/${personaId}`,
  GET_PERSONAS_BY_PROJECT: (projectId: string) => `/project/${projectId}/personas`,
  CREATE_LOCATION: (projectId: string) => `/project/${projectId}/location`,
  GET_LOCATION: (projectId: string, locationId: string) => `/project/${projectId}/location/${locationId}`,
  UPDATE_LOCATION: (projectId: string, locationId: string) => `/project/${projectId}/location/${locationId}`,
  DELETE_LOCATION: (projectId: string, locationId: string) => `/project/${projectId}/location/${locationId}`,
  GET_LOCATIONS_BY_PROJECT: (projectId: string) => `/project/${projectId}/locations`,
  CREATE_BRAND: (projectId: string) => `/project/${projectId}/brand`,
  GET_BRAND: (projectId: string, brandId: string) => `/project/${projectId}/brand/${brandId}`,
  UPDATE_BRAND: (projectId: string, brandId: string) => `/project/${projectId}/brand/${brandId}`,
  DELETE_BRAND: (projectId: string, brandId: string) => `/project/${projectId}/brand/${brandId}`,
  GET_BRANDS_BY_PROJECT: (projectId: string) => `/project/${projectId}/brands`,
  GET_SEARCHES_BY_TRACKER: (projectId: string, trackerId: string) => `/project/${projectId}/tracker/${trackerId}/searches`,
  GET_SEARCH_DETAIL: (projectId: string, trackerId: string, searchId: string) => `/project/${projectId}/tracker/${trackerId}/search/${searchId}`,
  GET_SEARCH_PRODUCTS: (projectId: string, searchId: string) => `/project/${projectId}/search/${searchId}/products`,
  GET_PRODUCT: (projectId: string, productId: string) => `/project/${projectId}/product/${productId}`,
  GET_REPORT: (projectId: string) => `/project/${projectId}/report`,
  GET_TAGS_BY_PROJECT: (projectId: string) => `/project/${projectId}/tags`,
  DELETE_TAG: (projectId: string, tagId: string) => `/project/${projectId}/tag/${tagId}`,
  GET_CITATION_DOMAINS: (projectId: string) => `/project/${projectId}/citation_domains`,
  GET_SEARCHLINK_DOMAINS: (projectId: string) => `/project/${projectId}/searchlink_domains`,
  GET_PERSONAS_REPORT: (projectId: string) => `/project/${projectId}/report/persona`,
  GET_LOCATION_REPORT: (projectId: string) => `/project/${projectId}/report/location`,
  GENERATE_KEYWORDS: `/onboarding/generate_keywords`,
  GENERATE_PROMPTS: `/onboarding/generate_prompts`,
  PAGE_AUDIT: (projectId: string) => `/project/${projectId}/audit`,
  GET_AUDITS: (projectId: string) => `/project/${projectId}/audit`,
  GET_AUDIT_DETAIL: (projectId: string, auditId: string) => `/project/${projectId}/audit/${auditId}`,
  WEB_INDEXING: (projectId: string) => `/project/${projectId}/web-indexing`,
  WEB_INDEXING_AUDIT: (projectId: string, auditId: string) => `/project/${projectId}/web-indexing/${auditId}`,
  GET_INSIGHTS: (projectId: string) => `/project/${projectId}/insights`,
  GENERATE_INSIGHTS: (projectId: string) => `/project/${projectId}/insights/generate`,
  UPDATE_INSIGHT: (projectId: string, insightId: string) => `/project/${projectId}/insight/${insightId}`,
  GET_ORG_PLAN: (orgId: string) => `/org/${orgId}/plan`,
  GET_LLM_MODELS: `/data/llm_models`,
  CREATE_BLOG_OUTLINE: (projectId: string) => `/project/${projectId}/blog-outline`,
  GET_BLOG_OUTLINES: (projectId: string) => `/project/${projectId}/blog-outlines`,
  GET_BLOG_OUTLINE: (projectId: string, topicId: string) => `/project/${projectId}/blog-outline/${topicId}`,
  UPDATE_BLOG_OUTLINE: (projectId: string, topicId: string) => `/project/${projectId}/blog-outline/${topicId}`,
  DELETE_BLOG_OUTLINE: (projectId: string, topicId: string) => `/project/${projectId}/blog-outline/${topicId}`,
  GET_TASKS: (projectId: string) => `/project/${projectId}/tasks`,
  DELETE_TASKS: (projectId: string) => `/project/${projectId}/task`,
};

